name:  gol_grid
description: A widget showing a controllable square grid of cellular automata.
version: 0.1.3
homepage: https://github.com/monopole/gol_grid

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  grid_world: ^0.1.10
  test: ^1.14.2
  thumper: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
